const mongoose = require("mongoose");

const userDetailsSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "user",
    required: true,
    index: true,
  },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  street: { type: String, required: true },
  city: { type: String, required: true },
  state: { type: String, required: true },
  country: { type: String, required: true },
  age: { type: Number, required: true },
  ethnicity: { type: String, required: true },
  race: { type: String, required: true },
  gender: { type: String, required: true },
  preferences: { type: String, required: true },
  type: { type: String, required: true },
  participant: { type: Number, required: true },
  weight: { type: Number, required: true },
  BMI: { type: Number, required: true },
  phone: { type: String, required: true },
  DOB: { type: Date, required: true },
  allergies: { type: String, required: true },
  moreEnergy: { type: Boolean, default: false },
  feelGoodAllDay: { type: Boolean, default: false },
  sleepBetter: { type: Boolean, default: false },
  reduceBellyFat: { type: Boolean, default: false },
  banishBodyFat: { type: Boolean, default: false },
  betterClearerSkin: { type: Boolean, default: false },
  getRidOfWrinkles: { type: Boolean, default: false },
  stopConstipation: { type: Boolean, default: false },
  getRidOfIndigestion: { type: Boolean, default: false },
  solveBloodSugarIssues: { type: Boolean, default: false },
  lowerCholesterol: { type: Boolean, default: false },
  reduceHighBloodPressure: { type: Boolean, default: false },
  getRidOfAnxiety: { type: Boolean, default: false },
  reverseAutoimmuneDisease: { type: Boolean, default: false },
  lookGoodForEvent: { type: Boolean, default: false },
  liveActiveHealthierLife: { type: Boolean, default: false },
  recoverAfterOverindulgence: { type: Boolean, default: false },
  description: { type: String, required: true },
  history: { type: String, required: true },
  medicationHistory: { type: String, required: true },
  mentalHealth: { type: String, required: true },
  sedimentation_rate: { type: String, required: true },
  cbc: { type: String, required: true },
  fasting_glucose: { type: String, required: true },
  bun: { type: String, required: true },
  creatinine: { type: String, required: true },
  calcium: { type: String, required: true },
  lipid_panel: { type: String, required: true },
  triglycerides: { type: String, required: true },
  hdl: { type: String, required: true },
  cholesterol: { type: String, required: true },
  ldl: { type: String, required: true },
  hba1c: { type: String, required: true },
  vit_d: { type: String, required: true },
  b12: { type: String, required: true },
  homocysteine: { type: String, required: true },
  tft_thyroid: { type: String, required: true },
  testType: { type: String,  },
  testReport: { type: String,  },
});

const UserDetails = mongoose.model("UserDetails", userDetailsSchema);

module.exports = UserDetails;
